"""Add GitHub integration fields to User model

Revision ID: a130d5806a8f
Revises: b2c3d4e5f6g7
Create Date: 2025-10-02 21:05:47.979907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a130d5806a8f'
down_revision = 'b2c3d4e5f6g7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_team_member_id', table_name='events')
    op.drop_index('idx_events_timestamp', table_name='events')
    op.drop_constraint('tasks_task_author_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['task_author_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('github_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('github_avatar_url', sa.Unicode(length=500), nullable=True))
    op.add_column('users', sa.Column('github_access_token', sa.Unicode(length=500), nullable=True))
    op.create_unique_constraint(None, 'users', ['github_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'github_access_token')
    op.drop_column('users', 'github_avatar_url')
    op.drop_column('users', 'github_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_task_author_id_fkey', 'tasks', 'users', ['task_author_id'], ['id'])
    op.create_index('idx_events_timestamp', 'events', ['timestamp'], unique=False)
    op.create_index('idx_events_team_member_id', 'events', ['team_member_id'], unique=False)
    # ### end Alembic commands ###
